version: b{build}
skip_tags: true
environment:
  matrix:
  - PUZZLES_PROJECT: PuzzleModern.Phone/PuzzleModern.Phone.vcxproj /p:Platform=ARM
    BUILD_WIN8: true
  - PUZZLES_PROJECT: PuzzleModern/PuzzleModern.vcxproj
    BUILD_WIN8: true

for:
-
  environment:
    only: BUILD_WIN8
  
  image: Visual Studio 2015

build_script:
- cmd: msbuild %PUZZLES_PROJECT% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:AppxPackageSigningEnabled=false
test: off
deploy: off
