version: b{build}
skip_tags: true
image: Visual Studio 2015
environment:
  matrix:
  - PUZZLES_PROJECT: PuzzleModernPhone/PuzzleModern.Phone/PuzzleModern.Phone.vcxproj /p:Platform=ARM
  - PUZZLES_PROJECT: PuzzleModern/PuzzleModern/PuzzleModern.vcxproj
build_script:
- cmd: msbuild %PUZZLES_PROJECT% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /p:AppxPackageSigningEnabled=false
test: off
deploy: off
